apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire
  template:
    metadata:
      labels:
        app: revhire
    spec:
      containers:
        - name: revcont
          image: hemanth097/revhirerepo:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: revhire-service
spec:
  type: NodePort
  selector:
    app: revhire
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 8000
      NodePort: 30000